name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    container: rust:1.88-bookworm
    steps:
      - uses: actions/checkout@v6

      - name: Check
        run: cargo check --release

      - name: Clippy
        run: cargo clippy --release -- -D warnings

      - name: Format
        run: cargo fmt -- --check

      - name: Test
        run: cargo test

  build:
    runs-on: ubuntu-latest
    container: rust:1.88-bookworm
    needs: check
    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: sc
          path: target/release/sc
